/**
 * Star.Web.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * DTO отчета.
 */
export interface ReportDto {
    /**
     * Группа отчета.
     */
    group?: models.ReportGroupDto;

    /**
     * Идентификатор сущности.
     */
    uid?: string;

    /**
     * Наименование отчета.
     */
    name?: string;

    /**
     * Вызов с объекта.
     */
    callFromObject?: boolean;

    /**
     * Вызов из главного меню.
     */
    callFromMenu?: boolean;

    /**
     * Предаварительный просмотр при генерации.
     */
    previewOnGeneration?: boolean;

    /**
     * Иконка.
     */
    iconId?: number;

    /**
     * Отчет без обязательных параметров, для которых не задано значение по-умолчанию.
     */
    hasNoRequiredAndDefaultParams?: boolean;

}
